# Generated by Django 3.1 on 2020-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to='recipes.Recipe'),
        ),
    ]
